[general]
# import = [
# "~/.config/alacritty/themes/themes/smoooooth.toml"
# ]

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 10.5

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
padding = {x = 0, y = 0}
